pipeline {
    agent {
        kubernetes {
          containerTemplate {
            name 'maven'
            image 'maven:3.8.6-openjdk-11-slim'
            command 'sleep'
            args '99d'
          }
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
